export const courses = [
  {
    id: crypto.randomUUID(),
    title: 'IT Training & Online MBA/BBA Guidance',
    slug: 'it-training',
    category: 'IT & Management',
    tag: 'Training & Courses',
    tagClass: 'bg-main-three-600',
    image: '/assets/images/thumbs/faculty-img1.png',
    duration: 200,
    features: [
      'Specialized IT Training',
      'Online MBA Courses',
      'Online BBA Courses',
      'Expert Faculties',
    ],
    isLinkCategory: true,
    link: '/courses/it-training',
  },
  {
    id: crypto.randomUUID(),
    title: 'Admission for Abroad University / Colleges',
    slug: 'abroad-education',
    category: 'Abroad University',
    tag: 'Global Opportunities',
    tagClass: 'bg-main-two-600',
    image: '/assets/images/all/Rejent-European-University.jpg',
    duration: 400,
    features: [
      'Rejent European University (San Marino)',
      'Southern Connecticut State University',
      'School of Business',
      'Global Exposure',
    ],
    isLinkCategory: true,
    link: '/courses/abroad-education',
  },
  {
    id: crypto.randomUUID(),
    title: 'Medical, NEET & KCET Guidance',
    slug: 'medical-admission',
    category: 'Medical & Engineering',
    tag: 'Pro Guidance',
    tagClass: 'bg-main-three-600',
    image: '/assets/images/all/RR-Medical-College.jpg',
    duration: 600,
    features: [
      'MBBS / MD / MS Guidance',
      'KEA / All India Registration Support',
      'Management Quota in Top Colleges',
      'Complete Admission Coordination',
    ],
    isLinkCategory: true,
    link: '/courses/medical-admission',
  },
  {
    id: crypto.randomUUID(),
    title: 'Engineering Admissions (All Branches)',
    slug: 'engineering-admission',
    category: 'B.Tech / B.E',
    tag: 'Top Colleges',
    tagClass: 'bg-main-two-600',
    image: '/assets/images/all/RV-College-Engineering.jpg',
    duration: 200,
    features: [
      'Computer Science (CSE)',
      'Information Science (ISE)',
      'Electronics (ECE)',
      'Mechanical & Civil',
    ],
    isLinkCategory: true,
    link: '/courses/engineering-admission',
  },
  {
    id: crypto.randomUUID(),
    title: 'Management Quota Admissions',
    slug: 'management-admission',
    category: 'Management',
    tag: 'Direct Admission',
    tagClass: 'bg-main-three-600',
    image: '/assets/images/all/christ-university-y.jpg',
    duration: 400,
    features: [
      'MBA / PGDM Direct Admission',
      'BBA / B.Com / BCA',
      'Top B-Schools Selection',
      'Placement Assistance',
    ],
    isLinkCategory: true,
    link: '/courses/management-admission',
  },
  {
    id: crypto.randomUUID(),
    title: 'Pharmacy, Nursing & Physiotherapy',
    slug: 'pharmacy-nursing',
    category: 'Healthcare',
    tag: 'Career Oriented',
    tagClass: 'bg-main-two-600',
    image: '/assets/images/all/ms-ramaiha.jpg',
    duration: 600,
    features: [
      'B.Pharm / D.Pharm',
      'B.Sc Nursing / GNM',
      'Bachelor of Physiotherapy (BPT)',
      'Allied Health Sciences',
    ],
    isLinkCategory: true,
    link: '/courses/pharmacy-nursing',
  },
];
